#!/usr/bin/env python3
"""Behavioural oracle for the 2026-10 Python tooling upgrade (plan section 11). Stdlib only.

"No functionality lost" is made measurable here: a snapshot records what the repo DOES through
its interfaces (tests, entry points, the MCP surface, importable names, the guardrail verdicts,
documented commands, non-Python files, test strength, coverage), and `compare` says per
component whether a later tree still does the same.

    oracle.py inventory [--check] [--verify-proofs]   classify every tracked .py (G0.P2)
    oracle.py snapshot <label> [--ref REF] [--runs N] [--components O1,O3,...] [--modules m,...]
    oracle.py compare <a> <b> [--components ...] [--partial]
    oracle.py ast-equal <parent> <commit>             class-B proof (O2)
    oracle.py impacted <commit>                       tests to run for a commit (section 10)
    oracle.py verify-snapshot <label> [--suite-runs N]
    oracle.py selftest-d14                            remove a public function, expect O5 DIFF
    oracle.py mcp-stdio                               list MCP tools over stdio (.mcp.json)
    oracle.py assert-stdlib                           the oracle imports only the stdlib

Every snapshot runs in a THROWAWAY worktree of the ref (its own `uv sync --frozen` venv), so
nothing a probe does -- a script writing state, a checker refreshing a baseline -- can touch
the working tree the oracle lives in. Every subprocess gets the same scrubbed environment with
REDIS_DB=15 (invariant I12: never canonical db 0).
"""
from __future__ import annotations

import argparse
import ast
import contextlib
import fnmatch
import hashlib
import inspect
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import tomllib
import warnings
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SNAPSHOTS = HERE / "snapshots"
PLUGIN_DIR = HERE / "pytest_plugin"
INVENTORY = HERE / "inventory.json"
INTENDED = HERE / "INTENDED_CHANGES.md"
G0_BASE_FILE = HERE / "G0_BASE"
BRANCH = "chore/tooling-upgrade-2026-10"

COMPONENTS = ("O1", "O2", "O3", "O4", "O5", "O6", "O7", "O8", "O9", "O10")
HISTORY_TREES = ("research/", "docs/library/", "docs/_archive/", "chronicles/", "fences/",
                 "session_logs/")
RUNTIME_ROOTS = ("core/", "agent/", "arsenal/")
TOOLING_ROOTS = ("tooling-upgrade/", "scripts/githooks/", "scripts/checkers/",
                 "scripts/generators/")
COVERAGE_SOURCES = ("core", "agent", "arsenal", "scripts")
COVERAGE_VERSION = "7.16.2"
IMPORT_TIMEOUT_S = 20
HELP_TIMEOUT_S = 20
CHECKER_TIMEOUT_S = 900
SUITE_TIMEOUT_S = 3 * 3600

# O7: the no-side-effect commands the quick starts document (README, AGENTS, CONTRIBUTING,
# docs/DEPLOY.md). bridge_doctor.py is documented too but POSTs its report to a peer, so it is
# deliberately absent. Keys are stable ids; argv is relative to the tree's venv python.
DOC_COMMANDS = {
    "agent_cli.status": ["agent_cli.py", "status"],
    "agent_cli.help": ["agent_cli.py", "--help"],
    "agent_cli.task-list": ["agent_cli.py", "task", "list"],
    "bootstrap.agent-init": ["bootstrap.py", "--agent-init"],
    "embedded_redis.status": ["-m", "core.foundation.embedded_redis", "--status"],
}

# O8: non-Python paths a tooling upgrade may change (plan section 11, O8 row). The plan copy is
# added by G0.P1 itself; the derived docs are the pre-commit generators' outputs.
O8_ALLOWLIST = (
    "pyproject.toml", "uv.lock", ".python-version", "requirements*.txt", "requirements/**",
    "pytest.ini", ".github/**", ".pre-commit-config.yaml", ".git-blame-ignore-revs",
    ".mcp.json", ".claude/settings.json", ".gitignore", "scripts/githooks/*", "tooling-upgrade/**",
    "docs/python-tooling-upgrade-plan-2026-10.md",
    # G5.P4 docs
    "README.md", "CONTRIBUTING.md", "AGENTS.md", "docs/DEPLOY.md",
    # generated docs, regenerated by their own generators (scripts/githooks/pre_commit.py)
    "docs/MODULE_INDEX.md", "docs/PHYSICS.md", "docs/MAP.md", "docs/DOORS.md", "docs/PRIOR_ART.md",
)

# Static calls that may sit at module top level without making an import side-effectful.
_SAFE_TOPLEVEL_CALLS = re.compile(
    r"^(sys\.path\.(insert|append|extend)|os\.environ\.setdefault|warnings\.\w+|"
    r"logging\.(basicConfig|getLogger)|__all__\.\w+)$")


# ----------------------------------------------------------------------------- small helpers

def run(cmd, cwd=ROOT, env=None, timeout=None, check=False, capture=True):
    r = subprocess.run([str(c) for c in cmd], cwd=str(cwd), env=env, timeout=timeout,
                       stdin=subprocess.DEVNULL, capture_output=capture, text=True,
                       encoding="utf-8", errors="replace")
    if check and r.returncode != 0:
        raise RuntimeError("command failed (%d): %s\n%s%s" % (
            r.returncode, " ".join(map(str, cmd)), r.stdout, r.stderr))
    return r


def run_logged(cmd, log: Path, cwd=ROOT, env=None, timeout=None):
    """run() for long steps: output goes to `log` AS IT IS PRODUCED (stdout+stderr merged), so
    the log's tail shows a suite moving -- a stuck run and a slow one are told apart by watching
    it grow. Returns a CompletedProcess whose stdout is the whole log."""
    log.parent.mkdir(parents=True, exist_ok=True)
    progress("step started: %s  (tail -f %s)" % (" ".join(map(str, cmd))[:120], log))
    with open(log, "w", encoding="utf-8") as fh:
        p = subprocess.Popen([str(c) for c in cmd], cwd=str(cwd), env=env,
                             stdin=subprocess.DEVNULL, stdout=fh, stderr=subprocess.STDOUT)
        try:
            rc = p.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            p.kill()
            p.wait()
            raise
    text = log.read_text(encoding="utf-8", errors="replace")
    progress("step finished: exit %d, %d log lines" % (rc, text.count("\n")))
    return subprocess.CompletedProcess(cmd, rc, text, "")


def progress(msg: str) -> None:
    print("[%s] %s" % (time.strftime("%H:%M:%S"), msg), flush=True)


def git(*args, cwd=ROOT, check=True):
    return run(["git", *args], cwd=cwd, check=check).stdout


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def sha256_file(p: Path) -> str:
    return sha256_bytes(Path(p).read_bytes())


def dump_json(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=1, sort_keys=True, ensure_ascii=False) + "\n",
                    encoding="utf-8", newline="\n")


def load_json(path: Path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def venv_python(tree: Path) -> Path:
    win = tree / ".venv" / "Scripts" / "python.exe"
    return win if win.exists() else tree / ".venv" / "bin" / "python"


def oracle_env(extra=None) -> dict:
    """The one environment every probe runs in: the caller's, scrubbed of anything that would
    make a run depend on who launched it, plus REDIS_DB=15 and a fixed terminal size."""
    env = {k: v for k, v in os.environ.items()
           if not (k.startswith(("PYTHON", "REDIS_", "AKASHIC_", "UV_", "PYTEST", "COV_"))
                   or k in ("VIRTUAL_ENV", "COLUMNS", "LINES", "CONDA_PREFIX"))}
    env.update({"REDIS_DB": "15", "COLUMNS": "80", "LINES": "24"})
    env.update(extra or {})
    return env


def normalize_text(s: str, tree: Path | None = None) -> str:
    """Whitespace-normalised, path-neutral text: what O4/O6/O7 compare."""
    for root in filter(None, (tree, ROOT)):
        for form in {str(root), Path(root).as_posix()}:
            s = s.replace(form, "<ROOT>")
    home = str(Path.home())
    s = s.replace(home, "<HOME>").replace(Path(home).as_posix(), "<HOME>")
    s = re.sub(r"0x[0-9a-fA-F]{6,}", "0x?", s)
    lines = [" ".join(ln.split()) for ln in s.replace("\r\n", "\n").split("\n")]
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def tracked_files(cwd=ROOT, ref=None):
    if ref:
        out = git("ls-tree", "-r", "-z", "--name-only", ref, cwd=cwd)
    else:
        out = git("ls-files", "-z", cwd=cwd)
    return sorted(p for p in out.split("\0") if p)


def g0_base() -> str:
    return G0_BASE_FILE.read_text(encoding="utf-8").strip()


def relevant_digest(commit: str, cwd=ROOT) -> str:
    """Digest of everything that can change behaviour at `commit`: every tracked blob except the
    oracle's own bookkeeping (non-.py files under tooling-upgrade/). A suite record or snapshot is
    current for HEAD iff its digest equals HEAD's."""
    out = git("ls-tree", "-r", commit, cwd=cwd)
    keep = []
    for line in out.splitlines():
        meta, path = line.split("\t", 1)
        if path.startswith("tooling-upgrade/") and not path.endswith(".py"):
            continue
        keep.append(meta.split()[2] + " " + path)
    return sha256_bytes("\n".join(keep).encode())


# ----------------------------------------------------------------------------- source analysis

def parse_file(path: Path):
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")   # invalid escapes in archived code are not ours to fix
            return ast.parse(path.read_bytes(), filename=str(path))
    except (SyntaxError, ValueError):
        return None


def dotted_name(rel: str):
    """'core/foo/bar.py' -> 'core.foo.bar'; '__init__' collapses; None if not identifier-safe."""
    parts = rel[:-3].split("/")
    if parts[-1] == "__init__":
        parts = parts[:-1]
    if not parts or not all(p.isidentifier() for p in parts):
        return None
    return ".".join(parts)


def is_history(rel: str) -> bool:
    return rel.startswith(HISTORY_TREES)


def has_main_guard(tree) -> bool:
    for node in tree.body if tree else ():
        if isinstance(node, ast.If):
            t = ast.unparse(node.test).replace("'", '"')
            if "__name__" in t and '"__main__"' in t:
                return True
    return False


def uses_argparse(tree) -> bool:
    for node in ast.walk(tree) if tree else ():
        if isinstance(node, ast.Import) and any(a.name == "argparse" for a in node.names):
            return True
        if isinstance(node, ast.ImportFrom) and node.module == "argparse":
            return True
    return False


def import_safe(tree) -> tuple[bool, str]:
    """Can importing this module run it? A top-level call that is not a known-benign set-up call
    (sys.path, warnings, logging) means the import IS the run -- the oracle never does that."""
    if tree is None:
        return False, "unparseable"
    for node in tree.body:
        if isinstance(node, ast.Expr):
            if isinstance(node.value, ast.Constant):
                continue
            if isinstance(node.value, ast.Call):
                name = ast.unparse(node.value.func)
                if _SAFE_TOPLEVEL_CALLS.match(name):
                    continue
                return False, "top-level call %s()" % name
            if isinstance(node.value, (ast.Await, ast.Yield)):
                return False, "top-level await"
            continue
        if isinstance(node, (ast.For, ast.AsyncFor, ast.While, ast.With, ast.AsyncWith)):
            return False, "top-level %s block" % type(node).__name__
    return True, ""


def top_level_bindings(tree, include_imports=False) -> set[str]:
    """Names bound at module top level (walking into if/try/with, never into defs)."""
    names: set[str] = set()

    def targets(t):
        if isinstance(t, ast.Name):
            names.add(t.id)
        elif isinstance(t, (ast.Tuple, ast.List)):
            for e in t.elts:
                targets(e)
        elif isinstance(t, ast.Starred):
            targets(t.value)

    def visit(body):
        for node in body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                names.add(node.name)
            elif isinstance(node, ast.Assign):
                for t in node.targets:
                    targets(t)
            elif isinstance(node, (ast.AnnAssign, ast.AugAssign)):
                targets(node.target)
            elif isinstance(node, (ast.Import, ast.ImportFrom)) and include_imports:
                for a in node.names:
                    if a.name != "*":
                        names.add((a.asname or a.name).split(".")[0])
            elif isinstance(node, ast.If):
                visit(node.body)
                visit(node.orelse)
            elif isinstance(node, ast.Try) or type(node).__name__ == "TryStar":
                visit(node.body)
                for h in node.handlers:
                    visit(h.body)
                visit(node.orelse)
                visit(node.finalbody)
            elif isinstance(node, (ast.With, ast.AsyncWith)):
                visit(node.body)
    visit(tree.body if tree else [])
    return names


def static_all(tree):
    for node in tree.body if tree else ():
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            tgts = node.targets if isinstance(node, ast.Assign) else [node.target]
            if any(isinstance(t, ast.Name) and t.id == "__all__" for t in tgts):
                try:
                    return sorted(set(ast.literal_eval(node.value)))
                except Exception:
                    return None
    return None


def static_signatures(tree) -> dict:
    sigs = {}
    for node in tree.body if tree else ():
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            full = "(%s)" % ast.unparse(node.args)
            if node.returns is not None:
                full += " -> " + ast.unparse(node.returns)
            bare_args = ast.parse("def f(%s): pass" % ast.unparse(node.args)).body[0].args
            for a in bare_args.posonlyargs + bare_args.args + bare_args.kwonlyargs:
                a.annotation = None
            for a in (bare_args.vararg, bare_args.kwarg):
                if a is not None:
                    a.annotation = None
            sigs[node.name] = {"full": full, "bare": "(%s)" % ast.unparse(bare_args)}
    return sigs


ANNOTATION_TRIGGERS = {
    "get_type_hints": "typing.get_type_hints", "__annotations__": "__annotations__",
    "signature": "inspect.signature", "dataclass": "dataclass", "dataclasses": "dataclass",
    "pydantic": "pydantic", "BaseModel": "pydantic", "FastMCP": "FastMCP",
}


def annotation_triggers(tree) -> list[str]:
    found = set()
    for node in ast.walk(tree) if tree else ():
        if isinstance(node, ast.Name) and node.id in ANNOTATION_TRIGGERS:
            found.add(ANNOTATION_TRIGGERS[node.id])
        elif isinstance(node, ast.Attribute) and node.attr in ANNOTATION_TRIGGERS:
            found.add(ANNOTATION_TRIGGERS[node.attr])
        elif isinstance(node, ast.ImportFrom) and node.module:
            top = node.module.split(".")[0]
            if top in ("pydantic", "dataclasses"):
                found.add(ANNOTATION_TRIGGERS[top])
            for a in node.names:
                if a.name in ANNOTATION_TRIGGERS:
                    found.add(ANNOTATION_TRIGGERS[a.name])
        elif isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] in ("pydantic", "dataclasses"):
                    found.add(ANNOTATION_TRIGGERS[a.name.split(".")[0]])
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for d in node.decorator_list:
                d = d.func if isinstance(d, ast.Call) else d
                if isinstance(d, ast.Attribute) and d.attr in ("tool", "resource", "prompt"):
                    found.add("@*.%s decorator" % d.attr)
    return sorted(found)


class RepoGraph:
    """Static import graph over the tracked .py files of one tree."""

    def __init__(self, tree_root: Path, files: list[str]):
        self.root = tree_root
        self.files = [f for f in files if f.endswith(".py")]
        self.asts = {f: parse_file(tree_root / f) for f in self.files}
        self.by_dotted = {}
        for f in self.files:
            d = dotted_name(f)
            if d:
                self.by_dotted.setdefault(d, f)
        self.edges = {f: set() for f in self.files}      # importer -> imported files
        self.ext_names = {}                               # file -> names others take from it
        for f in self.files:
            self._scan(f)

    def _resolve(self, importer: str, dotted: str) -> list[str]:
        hits = []
        parts = dotted.split(".")
        for i in range(1, len(parts) + 1):
            f = self.by_dotted.get(".".join(parts[:i]))
            if f:
                hits.append(f)
        # script-local import: a sibling module next to the importer (sys.path[0] is its dir)
        base = os.path.dirname(importer)
        for cand in (dotted.replace(".", "/") + ".py", dotted.replace(".", "/") + "/__init__.py"):
            rel = (base + "/" + cand) if base else cand
            if rel in self.asts:
                hits.append(rel)
        return hits

    def _scan(self, f: str) -> None:
        tree = self.asts[f]
        if tree is None:
            return
        pkg = f[:-3].split("/")[:-1]   # the importer's package (for __init__.py: its own dir)
        aliases = {}
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for a in node.names:
                    for hit in self._resolve(f, a.name):
                        self.edges[f].add(hit)
                    if a.asname:
                        aliases[a.asname] = a.name
                    else:
                        aliases[a.name.split(".")[0]] = a.name.split(".")[0]
                        aliases[a.name] = a.name
            elif isinstance(node, ast.ImportFrom):
                if node.level:
                    base = pkg[: len(pkg) - (node.level - 1)] if node.level > 1 else pkg
                    mod = ".".join(base + ([node.module] if node.module else []))
                else:
                    mod = node.module or ""
                targets = self._resolve(f, mod) if mod else []
                for hit in targets:
                    self.edges[f].add(hit)
                for a in node.names:
                    sub = self._resolve(f, mod + "." + a.name if mod else a.name)
                    sub = [s for s in sub if s not in targets]
                    if sub:
                        self.edges[f].update(sub)
                    elif targets and a.name != "*":
                        self.ext_names.setdefault(targets[-1], set()).add(a.name)
            elif isinstance(node, ast.Call):
                fn = ast.unparse(node.func)
                if (fn.endswith(("import_module", "__import__", "run_module"))
                        and node.args and isinstance(node.args[0], ast.Constant)
                        and isinstance(node.args[0].value, str)):
                    for hit in self._resolve(f, node.args[0].value):
                        self.edges[f].add(hit)
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute) and isinstance(node.value, (ast.Name, ast.Attribute)):
                owner = ast.unparse(node.value)
                if owner in aliases:
                    hits = self._resolve(f, aliases[owner])
                    if hits and not node.attr.startswith("_"):
                        self.ext_names.setdefault(hits[-1], set()).add(node.attr)

    def reverse(self) -> dict:
        rev = {f: set() for f in self.files}
        for src, dsts in self.edges.items():
            for d in dsts:
                rev.setdefault(d, set()).add(src)
        return rev


# ----------------------------------------------------------------------------- inventory (G0.P2)

_PATH_TOKEN = re.compile(r"[A-Za-z0-9_./\\-]+\.py\b")
_DOTTED_TOKEN = re.compile(r"\b[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+\b")


def _text_tokens(tree_root: Path, files: list[str]):
    """Per non-.py-or-.py tracked text file: the .py path tokens and dotted tokens it contains."""
    out = {}
    for f in files:
        p = tree_root / f
        try:
            if p.stat().st_size > 4_000_000:
                continue
            text = p.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        paths = {t.replace("\\", "/").lstrip("./") if not t.startswith("../") else
                 t.replace("\\", "/") for t in _PATH_TOKEN.findall(text)}
        dotted = set(_DOTTED_TOKEN.findall(text)) if f.endswith((".py", ".json", ".toml", ".yml",
                                                                 ".yaml", ".md", ".sh", ".ps1",
                                                                 ".cmd", ".bat", ".txt", ".cfg",
                                                                 ".ini")) or "/" not in f else set()
        out[f] = (paths, dotted)
    return out


def _referenced(cand: str, paths: set, unique_base: set) -> bool:
    base = cand.rsplit("/", 1)[-1]
    for t in paths:
        t2 = t.split("../")[-1]
        if t2 == cand or t2.endswith("/" + cand) or ("/" in t2 and cand.endswith("/" + t2)):
            return True
        if t2 == base and base in unique_base:
            return True
    return False


def classify(rel: str) -> str:
    if rel.startswith("tests/"):
        return "TEST"
    if rel.startswith(TOOLING_ROOTS):
        return "TOOLING"
    if rel.startswith("scripts/"):
        return "SCRIPT"
    if rel.startswith(RUNTIME_ROOTS) or "/" not in rel:
        return "RUNTIME"
    return "SCRIPT"


def build_inventory(tree_root: Path = ROOT) -> dict:
    files = tracked_files(tree_root)
    pys = [f for f in files if f.endswith(".py")]
    graph = RepoGraph(tree_root, pys)
    tokens = _text_tokens(tree_root, files)
    basenames = {}
    for f in pys:
        basenames.setdefault(f.rsplit("/", 1)[-1], []).append(f)
    unique_base = {b for b, fs in basenames.items() if len(fs) == 1}

    candidates = {f for f in pys if is_history(f)}
    # Fixpoint: a candidate that fails its proof is in scope, and then ITS imports and path
    # references count as non-archival evidence against the others.
    archival = set(candidates)
    rev = graph.reverse()
    proofs = {}
    changed = True
    while changed:
        changed = False
        # The oracle's own records (inventory.json, snapshots, ledger) list every path by design;
        # they are bookkeeping about the repo, not references from it, so they prove nothing.
        nonarch_files = [f for f in files if not (is_history(f) and (f in archival or not f.endswith(".py")))
                         and not (f.startswith("tooling-upgrade/") and not f.endswith(".py"))]
        for c in sorted(archival):
            importers = sorted(i for i in rev.get(c, ()) if i not in archival)
            refs = []
            dotted = dotted_name(c)
            for f in nonarch_files:
                if f == c or f not in tokens:
                    continue
                paths, dts = tokens[f]
                if _referenced(c, paths, unique_base) or (dotted and dotted in dts):
                    refs.append(f)
            proofs[c] = {"history_tree": next(h for h in HISTORY_TREES if c.startswith(h)),
                         "nonarchival_importers": importers, "path_refs": refs[:20],
                         "path_ref_count": len(refs)}
            if importers or refs:
                archival.discard(c)
                changed = True

    entries = {}
    for f in pys:
        tree = graph.asts[f]
        if f in archival:
            e = {"class": "ARCHIVAL", "proof": proofs[f]}
        else:
            e = {"class": classify(f)}
            if f in proofs:
                e["archival_rejected"] = {k: v for k, v in proofs[f].items() if v}
        safe, why = import_safe(tree)
        e.update({
            "module": dotted_name(f),
            "parse_ok": tree is not None,
            "main_guard": has_main_guard(tree),
            "argparse": uses_argparse(tree),
            "import_safe": safe,
        })
        if why:
            e["import_unsafe_reason"] = why
        trig = annotation_triggers(tree)
        if trig:
            e["annotation_triggers"] = trig
        e["lines"] = len((tree_root / f).read_bytes().splitlines())
        entries[f] = e

    in_scope = sorted(f for f, e in entries.items() if e["class"] != "ARCHIVAL")
    entry_points = sorted(f for f in in_scope
                          if entries[f]["main_guard"] and entries[f]["class"] != "TEST")
    sensitive = sorted(f for f in in_scope if entries[f].get("annotation_triggers")
                       and entries[f]["class"] != "TEST")
    req_consumers = sorted(f for f, (paths, _) in tokens.items()
                           if not is_history(f) and not f.startswith("tooling-upgrade/")
                           and _mentions_requirements(tree_root / f))
    counts = {}
    for e in entries.values():
        counts[e["class"]] = counts.get(e["class"], 0) + 1
    return {
        "schema": 1,
        "commit": git("rev-parse", "HEAD", cwd=tree_root).strip(),
        "counts": dict(sorted(counts.items())),
        "files": entries,
        "in_scope": in_scope,
        "archival": sorted(archival),
        "archival_excludes": _archival_dirs(archival, pys),
        "entry_points": {
            "main_modules": entry_points,
            "argparse_cli": [f for f in entry_points if entries[f]["argparse"]],
            "project_scripts": _project_scripts(tree_root),
            "hook_scripts": sorted(f for f in in_scope if f.startswith("scripts/githooks/")),
            "doc_commands": DOC_COMMANDS,
        },
        "annotation_sensitive": sensitive,
        "annotation_sensitive_protocol": sorted(
            f for f in sensitive if {"FastMCP", "@*.tool decorator"} & set(entries[f]["annotation_triggers"])),
        "requirements_consumers": req_consumers,
        "platforms": _platform_claims(tree_root),
        "tooling": _tooling_facts(tree_root),
        "smoke_tests": SMOKE_TESTS,
    }


# The always-run smoke set for the impacted oracle (section 10): fast tests that exercise the
# two doors (CLI, MCP), the store and the guardrail wiring.
SMOKE_TESTS = [
    "tests/test_mcp_arg_defaults_parity.py",
    "tests/test_tooling_upgrade_oracle.py",
]


def _mentions_requirements(p: Path) -> bool:
    try:
        t = p.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return bool(re.search(r"requirements(\.txt|/[\w.-]+\.txt)", t))


def _archival_dirs(archival: set, pys: list[str]) -> list[str]:
    """Smallest set of history-tree directories whose .py files are ALL archival (the only
    excludes T2 allows), plus single files where a directory also holds in-scope files."""
    out = []
    for h in HISTORY_TREES:
        in_tree = [f for f in pys if f.startswith(h)]
        if in_tree and all(f in archival for f in in_tree):
            out.append(h.rstrip("/"))
        else:
            out.extend(f for f in in_tree if f in archival)
    return sorted(out)


def _project_scripts(tree_root: Path) -> dict:
    try:
        data = tomllib.loads((tree_root / "pyproject.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return {}
    return data.get("project", {}).get("scripts", {})


def _platform_claims(tree_root: Path) -> list:
    claims = []
    for doc in ("README.md", "CONTRIBUTING.md", "AGENTS.md", "docs/DEPLOY.md"):
        p = tree_root / doc
        if not p.exists():
            continue
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            if re.search(r"\b(Windows|macOS|Linux|Python 3\.\d+)", line):
                claims.append({"file": doc, "line": i, "text": line.strip()[:200]})
    return claims


def _tooling_facts(tree_root: Path) -> dict:
    facts = {"config_files": sorted(
        f for f in tracked_files(tree_root)
        if f.rsplit("/", 1)[-1] in ("pyproject.toml", "pytest.ini", "setup.cfg", "tox.ini",
                                    "ruff.toml", ".ruff.toml", "pyrightconfig.json",
                                    ".coveragerc", ".pre-commit-config.yaml", ".python-version",
                                    "uv.lock", "ty.toml"))}
    ci = tree_root / ".github" / "workflows" / "ci.yml"
    if ci.exists():
        facts["ci_python"] = re.findall(r"python-version:\s*\"?([\d.]+)", ci.read_text(encoding="utf-8"))
    pv = tree_root / ".python-version"
    facts["python_version_file"] = pv.read_text(encoding="utf-8").strip() if pv.exists() else None
    st = tree_root / ".claude" / "settings.json"
    if st.exists():
        facts["claude_settings_python_flags"] = sorted(set(re.findall(
            r"(?:uv run|py)\s+(-p\s*[\d.]+|-3(?:\.\d+)?)", st.read_text(encoding="utf-8"))))
    hook = tree_root / "scripts" / "githooks" / "pre-commit"
    if hook.exists():
        facts["hook_launcher"] = "py -> uv run -> python3 (sh shim)" if "uv run" in hook.read_text(
            encoding="utf-8") else "unknown"
    vpy = venv_python(tree_root)
    facts["venv_python"] = run([vpy, "-c", "import sys;print(sys.version.split()[0])"]).stdout.strip() \
        if vpy.exists() else None
    facts["uv"] = run(["uv", "--version"]).stdout.strip()
    facts["full_suite"] = ("pytest -q over testpaths=tests (pytest.ini), serial, REDIS_DB=15, "
                           "--continue-on-collection-errors; the CI 'Test suite' step")
    return facts


def cmd_inventory(args) -> int:
    inv = build_inventory(ROOT)
    if args.check:
        old = load_json(INVENTORY)
        new = json.loads(json.dumps(inv, sort_keys=True))
        old.pop("commit", None)
        new.pop("commit", None)
        if old != new:
            print("INVENTORY STALE: regenerate with `oracle.py inventory`")
            for k in sorted(set(old) | set(new)):
                if old.get(k) != new.get(k):
                    print("   key differs:", k)
            changed = sorted(f for f in set(old.get("files", {})) | set(new["files"])
                             if old.get("files", {}).get(f) != new["files"].get(f))
            for f in changed[:20]:
                print("   file differs:", f)
            return 1
        print("INVENTORY CURRENT: %d files, %s" % (len(inv["files"]), inv["counts"]))
        return 0
    if args.verify_proofs:
        return verify_proofs(load_json(INVENTORY))
    dump_json(INVENTORY, inv)
    print("inventory: %d files %s -> %s" % (len(inv["files"]), inv["counts"],
                                            INVENTORY.relative_to(ROOT)))
    return 0


def verify_proofs(inv: dict) -> int:
    bad = []
    for f, e in inv["files"].items():
        if e["class"] != "ARCHIVAL":
            continue
        p = e.get("proof") or {}
        if (not f.startswith(HISTORY_TREES) or p.get("history_tree") is None
                or p.get("nonarchival_importers") != [] or p.get("path_ref_count") != 0):
            bad.append(f)
    n = sum(1 for e in inv["files"].values() if e["class"] == "ARCHIVAL")
    print("ARCHIVAL PROOFS: %d/%d complete" % (n - len(bad), n))
    for f in bad[:20]:
        print("  missing/failed proof:", f)
    return 1 if bad else 0


# ----------------------------------------------------------------------------- the run tree

def _rmtree(path: Path) -> None:
    def onerror(func, p, _exc):
        with contextlib.suppress(OSError):
            os.chmod(p, 0o700)
            func(p)
    shutil.rmtree(path, onerror=onerror)


@contextlib.contextmanager
def scratch_tree(ref: str, prefix: str = "aurora-scratch-"):
    """Like run_tree, at a random path: for work that never compares help text (measurements),
    so it can run while a snapshot holds the fixed path."""
    base = Path(tempfile.mkdtemp(prefix=prefix))
    tree = base / "aurora-scratch"
    git("worktree", "add", "--detach", str(tree), ref)
    try:
        run(["uv", "sync", "--frozen", "--quiet"], cwd=tree, env=oracle_env(), check=True,
            timeout=1800)
        yield tree
    finally:
        _rmtree(base)
        git("worktree", "prune", check=False)


def _owner_alive(o: dict) -> bool:
    """Is the process that owns the fixed run tree still alive? POSIX: signal 0. Windows has no
    harmless probe in the stdlib (os.kill terminates there), so a tree younger than the longest
    snapshot (6 h) counts as owned."""
    if os.name == "posix":
        try:
            os.kill(int(o.get("pid", 0)), 0)
            return True
        except (OSError, ValueError):
            return False
    return time.time() - float(o.get("started", 0)) < 6 * 3600


@contextlib.contextmanager
def run_tree(ref: str, python: str | None = None):
    """A detached throwaway worktree of `ref` with its own frozen venv. Removed afterwards by
    deleting the directory and pruning (never a forced git operation).

    The path is FIXED, not mkdtemp-random: argparse wraps defaults that embed it (e.g. a
    `--out-dir` default), and a random path would wrap differently on every snapshot. So only
    one snapshot runs at a time; a leftover tree from a crashed run is the oracle's own and is
    removed first."""
    base = Path(tempfile.gettempdir()) / "aurora-oracle-run"
    owner = base / "owner.json"
    if base.exists():
        if owner.exists() and _owner_alive(load_json(owner)):
            raise RuntimeError("another snapshot is running in %s (owner %s); one at a time"
                               % (base, owner.read_text(encoding="utf-8").strip()))
        _rmtree(base)   # a crashed run's leftover: the oracle's own scratch
        git("worktree", "prune", check=False)
    base.mkdir(parents=True)
    dump_json(owner, {"pid": os.getpid(), "started": time.time()})
    tree = base / "aurora-oracle"
    git("worktree", "add", "--detach", str(tree), ref)
    try:
        # `python`: measure a candidate interpreter (plan G1.P2) without committing a pin.
        run(["uv", "sync", "--frozen", "--quiet"] + (["--python", python] if python else []),
            cwd=tree, env=oracle_env(), check=True, timeout=1800)
        yield tree
    finally:
        _rmtree(base)
        git("worktree", "prune", check=False)


def git_status_set(tree: Path) -> set:
    out = run(["git", "status", "--porcelain", "--untracked-files=all"], cwd=tree).stdout
    return set(out.splitlines())


# ----------------------------------------------------------------------------- O1 test outcomes

def _final_outcome(rec: dict) -> str:
    if rec.get("setup") == "failed" or rec.get("teardown") == "failed":
        return "error"
    if rec.get("setup") == "skipped":
        return "skipped"
    return rec.get("call") or rec.get("setup") or "unknown"


def _pytest(tree: Path, args, out_json: Path, timeout, log: Path | None = None):
    env = oracle_env({"PYTHONPATH": str(PLUGIN_DIR), "AURORA_ORACLE_OUT": str(out_json)})
    cmd = [venv_python(tree), "-m", "pytest", *args, "-p", "aurora_oracle_plugin"]
    t0 = time.time()
    r = run_logged(cmd, log, cwd=tree, env=env, timeout=timeout) if log else \
        run(cmd, cwd=tree, env=env, timeout=timeout)
    data = load_json(out_json) if out_json.exists() else {"results": {}, "collect_errors": [],
                                                          "exitstatus": r.returncode}
    data["duration_s"] = round(time.time() - t0, 1)
    return r, data


def suite_runs(tree: Path, raw: Path, runs: int, reruns: int, select=()) -> dict:
    run_data, side_effects = [], []
    for i in range(1, runs + 1):
        out = raw / ("O1-run%d.json" % i)
        before = git_status_set(tree)
        progress("O1 suite run %d/%d" % (i, runs))
        r, data = _pytest(tree, ["-q", "-rfE", "-p", "no:cacheprovider",
                                 "--continue-on-collection-errors",
                                 "--junitxml=%s" % (raw / ("O1-run%d.xml" % i)), *select],
                          out, SUITE_TIMEOUT_S, log=raw / ("O1-run%d.log" % i))
        run_data.append(data)
        # what the suite does to the checkout it runs in (informational; never compared)
        side_effects.append(sorted(x[3:] for x in git_status_set(tree) - before))
    tests = {}
    for i, data in enumerate(run_data):
        for nid, rec in data["results"].items():
            tests.setdefault(nid, {"outcomes": [None] * runs})["outcomes"][i] = _final_outcome(rec)
    # Every id that did not pass somewhere is rerun alone, twice, so "fails reproducibly" is a
    # measured fact rather than a single-run accident.
    todo = [n for n, t in tests.items()
            if not all(o in ("passed", "skipped", "xfailed") for o in t["outcomes"] if o)]
    progress("O1 isolated reruns: %d ids x %d" % (len(todo), reruns))
    for k, nid in enumerate(sorted(todo)):
        t = tests[nid]
        if k % 10 == 0:
            progress("  rerun %d/%d" % (k + 1, len(todo)))
        t["reruns"] = []
        for k in range(reruns):
            out = raw / "rerun" / ("%s-%d.json" % (sha256_bytes(nid.encode())[:16], k))
            out.parent.mkdir(parents=True, exist_ok=True)
            _r, d = _pytest(tree, [nid, "-q", "-p", "no:cacheprovider", "-p", "no:randomly"],
                            out, 600)
            t["reruns"].append(_final_outcome(d["results"].get(nid, {})))
    for t in tests.values():
        t["class"] = o1_class(t["outcomes"])
    tests = {public_id(k): v for k, v in tests.items()}
    return {
        "runs": [{"exitstatus": d["exitstatus"], "duration_s": d["duration_s"],
                  "collect_errors": sorted(d["collect_errors"]), "counts": _counts(d),
                  "tree_side_effects": fx}
                 for d, fx in zip(run_data, side_effects)],
        "tests": tests,
    }


def _counts(data) -> dict:
    c = {}
    for rec in data["results"].values():
        o = _final_outcome(rec)
        c[o] = c.get(o, 0) + 1
    return dict(sorted(c.items()))


def o1_class(outcomes) -> str:
    seen = {o for o in outcomes if o is not None}
    if not seen:
        return "uncollected"
    if seen == {"passed"}:
        return "stable-pass"
    if seen <= {"failed", "error"}:
        return "stable-fail"
    if seen == {"skipped"}:
        return "skip"
    if seen == {"xfailed"}:
        return "xfail"
    return "flaky"


def fails_reproducibly(t: dict) -> bool:
    return (any(o in ("failed", "error") for o in t["outcomes"])
            and len(t.get("reruns", [])) >= 2
            and all(o in ("failed", "error", "unknown") for o in t["reruns"]))


def o1_ran(run) -> int:
    c = run["counts"]
    return c.get("passed", 0) + c.get("failed", 0) + c.get("error", 0)


def public_id(nid: str) -> str:
    """The node id as O1 stores it: parameter text replaced by its sha256 prefix. Parametrize
    ids can carry fixture VALUES -- this repo's secret-scanner tests parametrize on fake
    credential-shaped strings -- and copying them into a tracked snapshot moves them out of the
    files check_secrets allowlists. Hashing keeps matching exact and the values where they are."""
    if "[" in nid and nid.endswith("]") and "[#" not in nid:
        base, params = nid.split("[", 1)
        return "%s[#%s]" % (base, sha256_bytes(params[:-1].encode("utf-8"))[:12])
    return nid


def id_base(nid: str) -> str:
    return nid.split("[", 1)[0]


def _per_run(s) -> list:
    """[{base: {id: outcome}}] for each run."""
    out = [{} for _ in s["runs"]]
    for nid, t in s["tests"].items():
        for i, o in enumerate(t["outcomes"]):
            if o is not None and i < len(out):
                out[i].setdefault(id_base(nid), {})[nid] = o
    return out


def volatile_bases(s) -> set:
    """Parametrized tests whose ids differ between runs of ONE snapshot (an id built from a
    timestamp or a fresh signature): they can only be compared by count, never by id."""
    runs = _per_run(s)
    bases = set().union(*runs) if runs else set()
    return {b for b in bases if len({frozenset(r.get(b, {})) for r in runs}) > 1}


def compare_o1(a, b, partial=False) -> list:
    diffs = []
    volatile = volatile_bases(a) | volatile_bases(b)
    ra, rb = _per_run(a), _per_run(b)
    for base in sorted(volatile):
        cnt = lambda runs: min((len(r.get(base, {})) for r in runs), default=0)  # noqa: E731
        ok = lambda runs: min((sum(o == "passed" for o in r.get(base, {}).values()) for r in runs),  # noqa: E731
                              default=0)
        if cnt(rb) < cnt(ra):
            diffs.append(("volatile:" + base, "collects %d < baseline %d per run" % (cnt(rb), cnt(ra))))
        elif ok(rb) < ok(ra):
            diffs.append(("volatile:" + base, "passes %d < baseline %d per run" % (ok(rb), ok(ra))))
    for nid, t in sorted(a["tests"].items()):
        if id_base(nid) in volatile:
            continue
        nb = b["tests"].get(nid)
        if nb is None or nb["class"] == "uncollected":
            diffs.append(("id:" + nid, "no longer collected"))
        elif t["class"] == "stable-pass" and fails_reproducibly(nb):
            diffs.append(("regressed:" + nid, "stable-pass now fails reproducibly"))
    skips = lambda s: max((r["counts"].get("skipped", 0) for r in s["runs"]), default=0)  # noqa: E731
    if skips(b) > skips(a):
        diffs.append(("skips", "skip count %d > baseline %d" % (skips(b), skips(a))))
    cerr = lambda s: max((len(r["collect_errors"]) for r in s["runs"]), default=0)  # noqa: E731
    if cerr(b) > cerr(a):
        diffs.append(("collect-errors", "collection errors %d > baseline %d" % (cerr(b), cerr(a))))
    ran = lambda s: min((o1_ran(r) for r in s["runs"]), default=0)  # noqa: E731
    if ran(b) < ran(a):
        diffs.append(("run-count", "tests run %d < baseline %d (T7)" % (ran(b), ran(a))))
    return diffs


def cmd_rekey_o1(args) -> int:
    """Rewrite a stored O1.json's ids into public_id form (idempotent; no re-measurement)."""
    p = snapshot_dir(args.label) / "O1.json"
    data = load_json(p)
    before = len(data["tests"])
    data["tests"] = {public_id(k): v for k, v in data["tests"].items()}
    if len(data["tests"]) != before:
        raise RuntimeError("rekey collided: %d -> %d ids" % (before, len(data["tests"])))
    dump_json(p, data)
    print("rekeyed %s: %d ids" % (p.relative_to(ROOT), before))
    return 0


# ----------------------------------------------------------------------------- O2 AST equality

def _norm_doc(s: str) -> str:
    return "\n".join(ln.rstrip() for ln in inspect.cleandoc(s).splitlines()).strip()


def ast_fingerprint(src: bytes) -> str:
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            if (body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant)
                    and isinstance(body[0].value.value, str)):
                body[0].value.value = _norm_doc(body[0].value.value)
    return ast.dump(tree, include_attributes=False)


def ast_equal(parent: str, commit: str, cwd=ROOT):
    out = git("diff", "--name-status", "--no-renames", parent, commit, "--", "*.py", cwd=cwd)
    results = []
    for line in out.splitlines():
        status, path = line.split("\t", 1)
        if status != "M":
            results.append((path, False, "status %s (a format commit only modifies)" % status))
            continue
        a = run(["git", "show", "%s:%s" % (parent, path)], cwd=cwd).stdout.encode("utf-8")
        b = run(["git", "show", "%s:%s" % (commit, path)], cwd=cwd).stdout.encode("utf-8")
        try:
            ok = ast_fingerprint(a) == ast_fingerprint(b)
            results.append((path, ok, "" if ok else "AST differs"))
        except SyntaxError as e:
            results.append((path, False, "unparseable: %s" % e))
    return results


def cmd_ast_equal(args) -> int:
    res = ast_equal(args.parent, args.commit)
    for path, ok, why in res:
        print("%s %s%s" % ("EQUAL" if ok else "DIFF ", path, (" (" + why + ")") if why else ""))
    n_ok = sum(1 for _, ok, _ in res if ok)
    print("AST: %d/%d EQUAL" % (n_ok, len(res)))
    return 0 if n_ok == len(res) else 1


def format_commits(a_commit: str, b_commit: str, cwd=ROOT):
    """Class-B commits between two snapshots: subject `style: ...` (not `style(lint): ...`)."""
    if not a_commit or not b_commit or a_commit == b_commit:
        return []
    out = git("log", "--format=%H %s", "%s..%s" % (a_commit, b_commit), cwd=cwd, check=False)
    return [ln.split(" ", 1)[0] for ln in out.splitlines() if ln.split(" ", 1)[1].startswith("style:")]


# ----------------------------------------------------------------------------- O3 + O5 imports

_PROBE = r'''
import importlib, importlib.util, inspect, json, os, re, sys
root, mod, rel, names_path, out_path = sys.argv[1:6]
sys.path.insert(0, root)
res = {"status": None}
def norm(s):
    s = s.replace(root, "<ROOT>").replace(root.replace(os.sep, "/"), "<ROOT>")
    return re.sub(r"0x[0-9a-fA-F]{6,}", "0x?", s)
try:
    if mod != "-":
        m = importlib.import_module(mod)
    else:
        spec = importlib.util.spec_from_file_location("_oracle_probe_", os.path.join(root, rel))
        m = importlib.util.module_from_spec(spec)
        sys.modules["_oracle_probe_"] = m
        spec.loader.exec_module(m)
    res["status"] = "OK"
except ModuleNotFoundError as e:
    top = (e.name or "").split(".")[0]
    local = top and (os.path.exists(os.path.join(root, top)) or os.path.exists(os.path.join(root, top + ".py")))
    optional = set(json.load(open(names_path, encoding="utf-8")).get("optional", []))
    res["status"] = "ImportError(optional-dep)" if (top in optional and not local) else "error:ModuleNotFoundError"
    res["detail"] = e.name
except BaseException as e:
    res["status"] = "error:" + type(e).__name__
    res["detail"] = norm(str(e))[:300]
if res["status"] == "OK":
    static = json.load(open(names_path, encoding="utf-8"))
    names = set(static["ext"])
    if isinstance(getattr(m, "__all__", None), (list, tuple)):
        names |= {n for n in m.__all__ if isinstance(n, str)}
        res["all"] = True
    else:
        names |= set(static["defined"])
    present, sigs = [], {}
    for n in sorted(names):
        if not hasattr(m, n):
            continue
        present.append(n)
        obj = getattr(m, n)
        if inspect.ismodule(obj) or not callable(obj):
            continue
        try:
            s = inspect.signature(obj)
        except (TypeError, ValueError):
            sigs[n] = {"full": "<none>", "bare": "<none>"}
            continue
        except Exception as e:
            sigs[n] = {"full": "<error %s>" % type(e).__name__, "bare": "<error>"}
            continue
        try:
            bare = s.replace(parameters=[p.replace(annotation=p.empty) for p in s.parameters.values()],
                             return_annotation=s.empty)
            sigs[n] = {"full": norm(str(s)), "bare": norm(str(bare))}
        except Exception as e:
            sigs[n] = {"full": norm(str(s)), "bare": "<error %s>" % type(e).__name__}
    res["names"] = present
    res["sigs"] = sigs
with open(out_path, "w", encoding="utf-8") as fh:
    json.dump(res, fh)
'''


def optional_import_names(tree: Path) -> set:
    """Import names of DECLARED optional dependencies: the pyproject dependency groups, the
    platform-marked dependencies, and what they pull in by name (torch) or the stdlib leaves
    out on some builds (tkinter). Any other missing module is an error, not an option."""
    names = {"torch", "transformers", "tkinter"}
    try:
        data = tomllib.loads((tree / "pyproject.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return names
    reqs = [r for g in data.get("dependency-groups", {}).values() for r in g if isinstance(r, str)]
    reqs += [r for r in data.get("project", {}).get("dependencies", []) if ";" in r]
    for r in reqs:
        dist = re.split(r"[\s<>=!~;\[]", r.strip(), maxsplit=1)[0]
        names.add(dist.lower().replace("-", "_").replace(".", "_"))
    return names


# O5 surface rule. The plan's literal rule is "__all__ if defined, else names not starting with
# _". Read literally over dir(module) it would count every `import os` as public surface, and
# G3's F401 wave (which removes unused imports by design) would then be an O5 DIFF in hundreds
# of modules. So O5 records: __all__ when defined; otherwise the names the module itself binds
# at top level (defs, classes, assignments); PLUS every name other in-repo code actually takes
# from the module (`from m import x`, `m.x`) even when m only imported it -- the re-exports the
# plan's F401 rule protects -- and, for package __init__ files, every imported name.
def surface_targets(inv: dict, modules=None):
    out = []
    for f in inv["in_scope"]:
        e = inv["files"][f]
        if e["class"] == "TEST":
            continue
        mod = e["module"] or f
        if modules and mod not in modules and f not in modules:
            continue
        out.append((f, e))
    return out


def probe_modules(tree: Path, inv: dict, graph: RepoGraph, raw: Path, modules=None):
    """O3 + O5 together: one fresh interpreter per module, 20 s each, in parallel."""
    targets = surface_targets(inv, modules)
    optional = sorted(optional_import_names(tree))
    py = venv_python(tree)
    probe = raw / "probe.py"
    probe.write_text(_PROBE, encoding="utf-8")
    work = raw / "probe"
    work.mkdir(parents=True, exist_ok=True)

    def one(item):
        f, e = item
        key = e["module"] or f
        tree_ast = graph.asts.get(f)
        defined = sorted(n for n in top_level_bindings(tree_ast, include_imports=f.endswith("__init__.py"))
                         if not n.startswith("_"))
        ext = sorted(n for n in graph.ext_names.get(f, ()) if not n.startswith("_"))
        static = {"ext": ext, "defined": defined, "optional": optional}
        if not e["import_safe"]:
            return key, f, {"status": "SKIPPED(%s)" % e.get("import_unsafe_reason", "unsafe")}, static, tree_ast
        h = sha256_bytes(f.encode())[:16]
        names_path, out_path = work / (h + ".names.json"), work / (h + ".out.json")
        names_path.write_text(json.dumps(static), encoding="utf-8")
        mod = e["module"] if e["module"] and not f.startswith(("data/", "state/")) else "-"
        try:
            # a fixed hash seed makes set/frozenset defaults print in one order (probe only;
            # the suite itself always runs with the interpreter's normal randomisation)
            run([py, probe, str(tree), mod, f, names_path, out_path], cwd=tree,
                env=oracle_env({"PYTHONHASHSEED": "0"}), timeout=IMPORT_TIMEOUT_S)
            res = load_json(out_path) if out_path.exists() else {"status": "error:no-result"}
        except subprocess.TimeoutExpired:
            res = {"status": "timeout"}
        return key, f, res, static, tree_ast

    progress("O3/O5 probing %d modules" % len(targets))
    with ThreadPoolExecutor(max_workers=min(12, (os.cpu_count() or 4))) as pool:
        results = list(pool.map(one, targets))
    o3, o5 = {}, {}
    for key, f, res, static, tree_ast in sorted(results, key=lambda r: r[0]):
        o3[key] = {"file": f, "status": res["status"]}
        if res.get("detail"):
            o3[key]["detail"] = res["detail"]
        if res["status"] == "OK":
            o5[key] = {"mode": "runtime", "names": res["names"], "sigs": res["sigs"]}
        else:
            names = static_all(tree_ast) or sorted(set(static["defined"]) | set(static["ext"]))
            o5[key] = {"mode": "static", "names": names, "sigs": static_signatures(tree_ast)}
    sensitive = sorted((inv["files"][f]["module"] or f) for f in inv["annotation_sensitive"])
    return {"modules": o3}, {"modules": o5, "sensitive": sensitive}


def compare_o3(a, b, partial=False) -> list:
    diffs = []
    for mod, r in sorted(a["modules"].items()):
        rb = b["modules"].get(mod)
        if rb is None:
            if not partial:
                diffs.append(("import:" + mod, "module no longer probed"))
        elif r["status"] == "OK" and rb["status"] != "OK":
            diffs.append(("import:" + mod, "OK -> %s" % rb["status"]))
    return diffs


def compare_o5(a, b, partial=False) -> list:
    diffs = []
    sensitive = set(a.get("sensitive", [])) | set(b.get("sensitive", []))
    for mod, s in sorted(a["modules"].items()):
        sb = b["modules"].get(mod)
        if sb is None:
            if not partial:
                diffs.append(("module:" + mod, "module surface gone"))
            continue
        for n in sorted(set(s["names"]) - set(sb["names"])):
            diffs.append(("name:%s.%s" % (mod, n), "public name disappeared"))
        if s.get("mode") != sb.get("mode"):
            continue
        for n, sig in sorted(s["sigs"].items()):
            sgb = sb["sigs"].get(n)
            if sgb is None:
                continue
            if sig["bare"] != sgb["bare"]:
                diffs.append(("sig:%s.%s" % (mod, n), "%s -> %s" % (sig["bare"], sgb["bare"])))
            elif sig["full"] != sgb["full"] and mod in sensitive:
                diffs.append(("annot:%s.%s" % (mod, n),
                              "annotation changed in an annotation-sensitive module"))
    return diffs


# ----------------------------------------------------------------------------- O4 surfaces

def add_parser_verbs(tree_ast) -> list:
    verbs = set()
    for node in ast.walk(tree_ast) if tree_ast else ():
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and node.func.attr == "add_parser" and node.args
                and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str)):
            verbs.add(node.args[0].value)
    return sorted(verbs)


_MCP_PROBE = r'''
import json, sys, os, importlib.util
root, rel, out_path = sys.argv[1:4]
sys.path.insert(0, root)
spec = importlib.util.spec_from_file_location("_oracle_mcp_", os.path.join(root, rel))
m = importlib.util.module_from_spec(spec)
sys.modules["_oracle_mcp_"] = m
spec.loader.exec_module(m)
server = next(v for v in vars(m).values() if type(v).__name__ == "FastMCP")
import anyio
tools = anyio.run(server.list_tools)
data = [t.model_dump(mode="json", exclude_none=True) for t in tools]
with open(out_path, "w", encoding="utf-8") as fh:
    json.dump(data, fh)
'''


def mcp_server_script(tree: Path):
    cfg = json.loads((tree / ".mcp.json").read_text(encoding="utf-8"))
    name, server = sorted(cfg["mcpServers"].items())[0]
    args = server.get("args", [])
    script = next((a for a in args if a.endswith(".py")), None)
    return name, server, script


def mcp_tools_inprocess(tree: Path, raw: Path):
    _name, _server, script = mcp_server_script(tree)
    probe = raw / "mcp_probe.py"
    probe.write_text(_MCP_PROBE, encoding="utf-8")
    out = raw / "mcp_tools.json"
    r = run([venv_python(tree), probe, str(tree), script, out], cwd=tree, env=oracle_env(),
            timeout=60)
    if r.returncode != 0 or not out.exists():
        raise RuntimeError("in-process MCP capture failed: " + (r.stderr or r.stdout)[-500:])
    return load_json(out)


def mcp_tools_stdio(tree: Path, timeout=IMPORT_TIMEOUT_S):
    """Fallback: launch the server as .mcp.json says (command `uv` -> the tree's venv python)
    and speak newline-delimited JSON-RPC: initialize, initialized, tools/list."""
    _name, server, script = mcp_server_script(tree)
    cmd = [str(venv_python(tree)), script] if server.get("command") == "uv" else \
        [server["command"], *server.get("args", [])]
    p = subprocess.Popen(cmd, cwd=str(tree), env=oracle_env(server.get("env")),
                         stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                         text=True, encoding="utf-8")
    msgs = [
        {"jsonrpc": "2.0", "id": 1, "method": "initialize",
         "params": {"protocolVersion": "2025-06-18", "capabilities": {},
                    "clientInfo": {"name": "aurora-oracle", "version": "1"}}},
        {"jsonrpc": "2.0", "method": "notifications/initialized"},
        {"jsonrpc": "2.0", "id": 2, "method": "tools/list"},
    ]
    try:
        p.stdin.write("".join(json.dumps(m) + "\n" for m in msgs))
        p.stdin.flush()
        deadline = time.time() + timeout
        tools, cursor_msgs = None, 0
        while time.time() < deadline:
            line = p.stdout.readline()
            if not line:
                break
            try:
                msg = json.loads(line)
            except json.JSONDecodeError:
                continue
            if msg.get("id") == 2:
                tools = msg.get("result", {}).get("tools")
                if msg.get("result", {}).get("nextCursor") and cursor_msgs < 50:
                    cursor_msgs += 1
                break
        if tools is None:
            raise RuntimeError("no tools/list response within %ss" % timeout)
        return tools
    finally:
        p.kill()
        p.wait(timeout=10)


def surface_o4(tree: Path, inv: dict, graph: RepoGraph, raw: Path) -> dict:
    helps, verbs = {}, {}
    before = git_status_set(tree)
    clis = inv["entry_points"]["argparse_cli"]
    for k, f in enumerate(clis):
        if k % 25 == 0:
            progress("O4 --help %d/%d" % (k + 1, len(clis)))
        try:
            r = run([venv_python(tree), f, "--help"], cwd=tree, env=oracle_env(),
                    timeout=HELP_TIMEOUT_S)
            item = {"rc": r.returncode, "text": normalize_text(r.stdout, tree)}
            if r.returncode != 0:
                err = normalize_text(r.stderr, tree).splitlines()
                item["stderr_last"] = err[-1] if err else ""
        except subprocess.TimeoutExpired:
            item = {"rc": None, "text": "", "na": "timeout under --help (%ss)" % HELP_TIMEOUT_S}
        after = git_status_set(tree)
        if after - before:
            item = {"rc": None, "text": "", "na": "side effect under --help: " +
                    ", ".join(sorted(x[3:] for x in after - before))[:300]}
            before = after
        helps[f] = item
        v = add_parser_verbs(graph.asts.get(f))
        if v:
            verbs[f] = v
    try:
        tools, via = mcp_tools_inprocess(tree, raw), "in-process"
    except Exception as e:  # plan G0 Fallback: capture over stdio with a 20 s timeout
        (raw / "mcp_inprocess_error.txt").write_text(str(e), encoding="utf-8")
        tools, via = mcp_tools_stdio(tree), "stdio"
    mcp = {t["name"]: {k: t[k] for k in sorted(t) if k in ("name", "description", "inputSchema",
                                                          "outputSchema", "annotations", "title")}
           for t in tools}
    return {"help": helps, "verbs": verbs, "mcp": {"via": via, "tools": mcp}}


def compare_o4(a, b, partial=False) -> list:
    diffs = []
    for f, h in sorted(a["help"].items()):
        hb = b["help"].get(f)
        if hb is None:
            if not partial:
                diffs.append(("help:" + f, "entry point gone"))
        elif any(h.get(k) != hb.get(k) for k in ("rc", "text", "na", "stderr_last")):
            diffs.append(("help:" + f, "--help output or exit code changed"))
    for f, v in sorted(a["verbs"].items()):
        missing = set(v) - set(b["verbs"].get(f, []))
        if missing:
            diffs.append(("verbs:" + f, "verbs gone: " + ", ".join(sorted(missing))))
    ta, tb = a["mcp"]["tools"], b["mcp"]["tools"]
    for name in sorted(set(ta) | set(tb)):
        if name not in tb:
            diffs.append(("mcp:" + name, "tool gone"))
        elif name not in ta:
            diffs.append(("mcp:" + name, "tool added"))
        elif json.dumps(ta[name], sort_keys=True) != json.dumps(tb[name], sort_keys=True):
            diffs.append(("mcp:" + name, "tool schema or description changed"))
    return diffs


# ----------------------------------------------------------------------------- O6 guardrails

def surface_o6(tree: Path, raw: Path) -> dict:
    out = {}
    for p in sorted((tree / "scripts" / "checkers").glob("*.py")):
        if p.name.startswith("_"):
            continue
        progress("O6 %s" % p.stem)
        try:
            r = run([venv_python(tree), p.relative_to(tree).as_posix()], cwd=tree,
                    env=oracle_env(), timeout=CHECKER_TIMEOUT_S)
            text = normalize_text(r.stdout + r.stderr, tree)
            item = {"rc": r.returncode, "crashed": "Traceback (most recent call last)" in text,
                    "lines": len(text.splitlines()), "digest": sha256_bytes(text.encode())}
            if r.returncode == 2 and "usage:" in text and "required" in text:
                item["na"] = "needs arguments"
            (raw / ("O6-%s.log" % p.stem)).write_text(text, encoding="utf-8")
        except subprocess.TimeoutExpired:
            item = {"rc": 999, "crashed": True, "lines": 0, "digest": "", "na": "timeout"}
        out[p.stem] = item
    return {"checkers": out}


def compare_o6(a, b, partial=False) -> list:
    diffs = []
    for name, r in sorted(a["checkers"].items()):
        rb = b["checkers"].get(name)
        if rb is None:
            diffs.append(("checker:" + name, "checker gone"))
            continue
        if rb["crashed"] and not r["crashed"]:
            diffs.append(("checker:" + name, "now crashes"))
        elif rb["rc"] > r["rc"]:
            diffs.append(("checker:" + name, "exit %d > baseline %d" % (rb["rc"], r["rc"])))
    return diffs


# ----------------------------------------------------------------------------- O7 documented commands

_HEADING = re.compile(r"^(#+ .*|=+ .* =+|[A-Za-z][\w /().,-]{0,60}:)$")


def headings(text: str) -> list:
    return sorted({re.sub(r"\d+", "9", ln) for ln in text.splitlines() if _HEADING.match(ln)})


def surface_o7(tree: Path) -> dict:
    out = {}
    for key, argv in sorted(DOC_COMMANDS.items()):
        try:
            r = run([venv_python(tree), *argv], cwd=tree, env=oracle_env(), timeout=120)
            text = normalize_text(r.stdout + r.stderr, tree)
            out[key] = {"rc": r.returncode, "lines": len(text.splitlines()),
                        "headings": headings(text)}
        except subprocess.TimeoutExpired:
            out[key] = {"rc": 999, "lines": 0, "headings": []}
    return {"commands": out}


def compare_o7(a, b, partial=False) -> list:
    diffs = []
    for key, r in sorted(a["commands"].items()):
        rb = b["commands"].get(key)
        if rb is None:
            diffs.append(("cmd:" + key, "command not captured"))
            continue
        if rb["rc"] != r["rc"]:
            diffs.append(("cmd:" + key, "exit %s -> %s" % (r["rc"], rb["rc"])))
        if abs(rb["lines"] - r["lines"]) > max(1, 0.1 * r["lines"]):
            diffs.append(("cmd:" + key, "output %d -> %d lines (>10%%)" % (r["lines"], rb["lines"])))
        if rb["headings"] != r["headings"]:
            diffs.append(("cmd:" + key, "headings changed"))
    return diffs


# ----------------------------------------------------------------------------- O8 non-Python files

def allowlisted(path: str) -> bool:
    return any(fnmatch.fnmatchcase(path, pat) or
               (pat.endswith("/**") and path.startswith(pat[:-2])) for pat in O8_ALLOWLIST)


def surface_o8(commit: str, cwd=ROOT) -> dict:
    base = g0_base()
    changed = git("diff", "--name-only", "--no-renames", base, commit, cwd=cwd).splitlines()
    non_py = sorted(p for p in changed if not p.endswith(".py"))
    return {"base": base, "changed_non_py": non_py,
            "violations": [p for p in non_py if not allowlisted(p)]}


def compare_o8(a, b, partial=False) -> list:
    return [("path:" + p, "non-Python file outside the tooling allowlist") for p in b["violations"]]


# ----------------------------------------------------------------------------- O9 test strength

def assertion_count(fn) -> int:
    n = 0
    for node in ast.walk(fn):
        if isinstance(node, ast.Assert):
            n += 1
        elif isinstance(node, (ast.With, ast.AsyncWith)):
            for item in node.items:
                c = item.context_expr
                if isinstance(c, ast.Call):
                    name = ast.unparse(c.func)
                    if name.endswith(("raises", "warns", "deprecated_call")):
                        n += 1
        elif isinstance(node, ast.Call):
            name = ast.unparse(node.func)
            last = name.rsplit(".", 1)[-1]
            if last.startswith("assert") or name in ("pytest.fail", "fail"):
                n += 1
    return n


def test_strength(tree_root: Path, files=None) -> dict:
    files = files or [f for f in tracked_files(tree_root) if f.startswith("tests/") and f.endswith(".py")]
    out = {}
    for f in files:
        tree = parse_file(tree_root / f)
        if tree is None:
            continue
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test"):
                out["%s::%s" % (f, node.name)] = assertion_count(node)
            elif isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
                for sub in node.body:
                    if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)) and sub.name.startswith("test"):
                        out["%s::%s::%s" % (f, node.name, sub.name)] = assertion_count(sub)
    return {"tests": dict(sorted(out.items())), "total": sum(out.values())}


def compare_o9(a, b, partial=False) -> list:
    diffs = []
    for k, n in sorted(a["tests"].items()):
        nb = b["tests"].get(k)
        if nb is None:
            diffs.append(("test:" + k, "test function gone"))
        elif nb < n:
            diffs.append(("test:" + k, "assertions %d -> %d" % (n, nb)))
    if b["total"] < a["total"]:
        diffs.append(("total", "total assertions %d -> %d" % (a["total"], b["total"])))
    return diffs


# ----------------------------------------------------------------------------- O10 coverage

def surface_o10(tree: Path, raw: Path, select=()) -> dict:
    data = raw / ".coverage"
    env = oracle_env()
    cmd = ["uv", "run", "--frozen", "--with", "coverage==" + COVERAGE_VERSION, "python", "-m",
           "coverage", "run", "--branch", "--source=" + ",".join(COVERAGE_SOURCES),
           "--data-file=" + str(data), "-m", "pytest", "-q", "-p", "no:cacheprovider",
           "--continue-on-collection-errors", *select]
    r = run_logged(cmd, raw / "O10-run.log", cwd=tree, env=env, timeout=SUITE_TIMEOUT_S)
    js = raw / "coverage.json"
    run(["uv", "run", "--frozen", "--with", "coverage==" + COVERAGE_VERSION, "python", "-m",
         "coverage", "json", "--data-file=" + str(data), "-o", str(js)], cwd=tree, env=env,
        check=True, timeout=600)
    files = load_json(js)["files"]
    agg = {}
    for path, d in files.items():
        rel = Path(path).resolve().relative_to(tree.resolve()).as_posix() if Path(path).is_absolute() else path.replace("\\", "/")
        pkg = rel.split("/", 1)[0]
        s = d["summary"]
        a = agg.setdefault(pkg, [0, 0])
        a[0] += s["covered_lines"] + s.get("covered_branches", 0)
        a[1] += s["num_statements"] + s.get("num_branches", 0)
    pct = {k: round(100.0 * c / t, 2) if t else 100.0 for k, (c, t) in sorted(agg.items())}
    return {"packages": pct, "suite_exitstatus": r.returncode, "coverage_version": COVERAGE_VERSION}


def compare_o10(a, b, partial=False) -> list:
    diffs = []
    for pkg, p in sorted(a["packages"].items()):
        pb = b["packages"].get(pkg)
        if pb is None or pb < p - 0.5:
            diffs.append(("cov:" + pkg, "%.2f -> %s (drop > 0.5 pp)" % (p, pb)))
    return diffs


# ----------------------------------------------------------------------------- snapshot / compare

def snapshot(label: str, ref: str = "HEAD", runs: int = 3, reruns: int = 2, components=None,
             modules=None, tree: Path | None = None, mutate=None, select=(),
             python: str | None = None) -> Path:
    components = components or list(COMPONENTS)
    dest = SNAPSHOTS / label
    raw = dest / "raw"
    raw.mkdir(parents=True, exist_ok=True)
    commit = git("rev-parse", ref).strip()
    ctx = run_tree(commit, python) if tree is None else contextlib.nullcontext(tree)
    with ctx as t:
        if mutate:
            mutate(t)
        dirty = bool(git_status_set(t))
        inv = build_inventory(t)
        graph = RepoGraph(t, [f for f in tracked_files(t) if f.endswith(".py")])
        tree_python = run([venv_python(t), "-c", "import sys;print(sys.version.split()[0])"]).stdout.strip()
        common = {"commit": commit, "digest": relevant_digest(commit), "dirty": dirty,
                  "created": time.strftime("%Y-%m-%dT%H:%M:%S%z"), "select": list(select)}

        def put(comp, data):
            data["_meta"] = dict(common, partial_modules=sorted(modules) if modules else None)
            dump_json(dest / (comp + ".json"), data)
            progress("%s captured" % comp)

        if "O8" in components:
            put("O8", surface_o8(commit))
        if "O9" in components:
            put("O9", test_strength(t))
        if "O2" in components:
            put("O2", {"note": "O2 is evaluated at compare time over the format commits between "
                               "the two snapshots (oracle.py ast-equal)."})
        if "O3" in components or "O5" in components:
            o3, o5 = probe_modules(t, inv, graph, raw, modules)
            if "O3" in components:
                put("O3", o3)
            if "O5" in components:
                put("O5", o5)
        if "O4" in components:
            put("O4", surface_o4(t, inv, graph, raw))
        if "O6" in components:
            put("O6", surface_o6(t, raw))
        if "O7" in components:
            put("O7", surface_o7(t))
        if "O10" in components:
            put("O10", surface_o10(t, raw, select))
        if "O1" in components:
            put("O1", suite_runs(t, raw, runs, reruns, select))
    meta_path = dest / "meta.json"
    meta = load_json(meta_path) if meta_path.exists() else {}
    meta.update({"label": label, "commit": commit, "digest": common["digest"], "dirty": dirty,
                 "python": run([sys.executable, "-c", "import sys;print(sys.version.split()[0])"]).stdout.strip(),
                 "tree_python": tree_python,
                 "platform": sys.platform, "uv": run(["uv", "--version"]).stdout.strip()})
    meta.setdefault("components", {})
    for c in components:
        meta["components"][c] = common["created"]
    meta["raw_digests"] = {p.relative_to(raw).as_posix(): sha256_file(p)
                           for p in sorted(raw.rglob("*")) if p.is_file()
                           and p.suffix in (".log", ".xml") and "rerun" not in p.parts}
    if "O1" in components:
        meta["suite_runs"] = runs
        meta["reruns"] = reruns
    dump_json(meta_path, meta)
    return dest


COMPARATORS = {"O1": compare_o1, "O3": compare_o3, "O4": compare_o4, "O5": compare_o5,
               "O6": compare_o6, "O7": compare_o7, "O8": compare_o8, "O9": compare_o9,
               "O10": compare_o10}


def load_intended() -> list:
    """INTENDED_CHANGES.md: one ```toml block per entry (id, component, key glob, reason)."""
    if not INTENDED.exists():
        return []
    text = INTENDED.read_text(encoding="utf-8")
    out = []
    for block in re.findall(r"```toml\n(.*?)```", text, flags=re.S):
        entry = tomllib.loads(block)
        if {"id", "component", "key", "reason"} <= set(entry):
            out.append(entry)
    return out


def compare_dirs(a: Path, b: Path, components=None, partial=False, intended=None):
    intended = load_intended() if intended is None else intended
    lines, equal = [], 0
    comps = components or list(COMPONENTS)
    for c in comps:
        if c == "O2":
            ma = load_json(a / "meta.json") if (a / "meta.json").exists() else {}
            mb = load_json(b / "meta.json") if (b / "meta.json").exists() else {}
            commits = format_commits(ma.get("commit"), mb.get("commit"))
            bad = []
            for sha in commits:
                bad += [p for p, ok, _ in ast_equal(sha + "^", sha) if not ok]
            if bad:
                lines.append("O2 DIFF %d %s" % (len(bad), ", ".join(bad[:5])))
            else:
                equal += 1
                lines.append("O2 EQUAL (%d format commits)" % len(commits))
            continue
        fa, fb = a / (c + ".json"), b / (c + ".json")
        if not fa.exists() or not fb.exists():
            lines.append("%s MISSING (%s)" % (c, fa if not fa.exists() else fb))
            continue
        diffs = COMPARATORS[c](load_json(fa), load_json(fb), partial)
        covered = [d for d in diffs if any(e["component"] == c and fnmatch.fnmatchcase(d[0], e["key"])
                                           for e in intended)]
        open_ = [d for d in diffs if d not in covered]
        if not open_:
            equal += 1
            ids = sorted({e["id"] for d in covered for e in intended
                          if e["component"] == c and fnmatch.fnmatchcase(d[0], e["key"])})
            lines.append("%s EQUAL%s" % (c, " (intended: %s)" % ", ".join(ids) if ids else ""))
        else:
            summary = "; ".join("%s: %s" % d for d in open_[:3])
            lines.append("%s DIFF %d %s" % (c, len(open_), summary))
    lines.append("ORACLE: %d/%d EQUAL" % (equal, len(comps)))
    return lines, equal == len(comps)


def snapshot_dir(label: str) -> Path:
    return SNAPSHOTS / ("head" if label == "HEAD" else label)


def cmd_snapshot(args) -> int:
    comps = args.components.split(",") if args.components else None
    mods = set(args.modules.split(",")) if args.modules else None
    sel = tuple(args.select.split(",")) if args.select else ()
    dest = snapshot(args.label, args.ref, args.runs, args.reruns, comps, mods, select=sel,
                    python=args.python)
    print("snapshot written: %s" % dest.relative_to(ROOT))
    return 0


def cmd_compare(args) -> int:
    comps = args.components.split(",") if args.components else None
    lines, ok = compare_dirs(snapshot_dir(args.a), snapshot_dir(args.b), comps, args.partial)
    print("\n".join(lines))
    return 0 if ok else 1


def verify_snapshot(label: str, suite_runs: int) -> list:
    d = snapshot_dir(label)
    problems = []
    if not (d / "meta.json").exists():
        return ["no meta.json in %s" % d]
    meta = load_json(d / "meta.json")
    for c in COMPONENTS:
        p = d / (c + ".json")
        if not p.exists():
            problems.append("%s missing" % c)
            continue
        m = load_json(p).get("_meta", {})
        if m.get("digest") != meta["digest"]:
            problems.append("%s taken at a different tree than meta.json" % c)
        if m.get("partial_modules"):
            problems.append("%s is a partial (module-restricted) capture" % c)
        if m.get("dirty"):
            problems.append("%s taken in a dirty tree" % c)
        if m.get("select"):
            problems.append("%s ran a test SELECTION, not the full suite" % c)
    if (d / "O1.json").exists() and len(load_json(d / "O1.json")["runs"]) < suite_runs:
        problems.append("O1 has fewer than %d suite runs" % suite_runs)
    if not meta.get("raw_digests"):
        problems.append("meta.json has no raw-log digests")
    return problems


def cmd_verify_snapshot(args) -> int:
    problems = verify_snapshot(args.label, args.suite_runs)
    for p in problems:
        print("  ", p)
    print("SNAPSHOT %s: %s" % (args.label, "COMPLETE" if not problems else "INCOMPLETE"))
    return 1 if problems else 0


# ----------------------------------------------------------------------------- impacted

def impacted(commit: str) -> list:
    changed = git("diff", "--name-only", commit + "^", commit, "--", "*.py").splitlines()
    pys = [f for f in tracked_files() if f.endswith(".py")]
    graph = RepoGraph(ROOT, pys)
    rev = graph.reverse()
    seen, stack = set(), [c for c in changed if c in graph.asts]
    while stack:
        f = stack.pop()
        if f in seen:
            continue
        seen.add(f)
        stack.extend(rev.get(f, ()))
    tests = {f for f in seen if f.startswith("tests/") and f.rsplit("/", 1)[-1].startswith("test")}
    tests |= {t for t in SMOKE_TESTS if (ROOT / t).exists()}
    return sorted(tests)


def cmd_impacted(args) -> int:
    for t in impacted(args.commit):
        print(t)
    return 0


# ----------------------------------------------------------------------------- self-tests

def _drop_function(tree: Path, inv: dict, base_o5: dict):
    """Pick the first core module (sorted) whose baseline surface has a public top-level def
    that exists in source, and delete that def. Returns (module, function)."""
    for mod in sorted(base_o5["modules"]):
        if not mod.startswith("core."):
            continue
        rel = next((f for f, e in inv["files"].items() if e["module"] == mod), None)
        if rel is None or rel.endswith("__init__.py"):
            continue
        src = (tree / rel).read_text(encoding="utf-8")
        t = ast.parse(src)
        for node in t.body:
            if (isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and node.name in base_o5["modules"][mod]["names"]):
                start = min([node.lineno] + [d.lineno for d in node.decorator_list])
                lines = src.splitlines(keepends=True)
                del lines[start - 1: node.end_lineno]
                (tree / rel).write_text("".join(lines), encoding="utf-8")
                return mod, node.name
    raise RuntimeError("no core module with a removable public function")


def cmd_selftest_d14(args) -> int:
    base = snapshot_dir(args.baseline)
    base_o5 = load_json(base / "O5.json")
    inv = load_json(INVENTORY)
    picked = {}

    def mutate(tree):
        picked["mod"], picked["fn"] = _drop_function(tree, inv, base_o5)
        print("D14 self-test: removed %s.%s in a scratch worktree" % (picked["mod"], picked["fn"]))

    label = "_selftest_d14"
    commit = git("rev-parse", "HEAD").strip()
    with scratch_tree(commit, "aurora-d14-") as t:
        mutate(t)
        graph = RepoGraph(t, [f for f in tracked_files(t) if f.endswith(".py")])
        raw = SNAPSHOTS / label / "raw"
        raw.mkdir(parents=True, exist_ok=True)
        _o3, o5 = probe_modules(t, load_json(INVENTORY), graph, raw, {picked["mod"]})
    diffs = compare_o5(base_o5, o5, partial=True)
    _rmtree(SNAPSHOTS / label)
    for k, why in diffs:
        print("O5 DIFF %s (%s)" % (k, why))
    hit = any(k == "name:%s.%s" % (picked["mod"], picked["fn"]) for k, _ in diffs)
    print("D14 SELF-TEST: %s" % ("O5 DIFF DETECTED" if hit else "MISSED"))
    return 0 if hit else 1


def cmd_mcp_stdio(args) -> int:
    commit = git("rev-parse", "HEAD").strip()
    with scratch_tree(commit, "aurora-mcp-") as t:
        tools = mcp_tools_stdio(t)
    print("MCP stdio: %d tools: %s" % (len(tools), ", ".join(sorted(x["name"] for x in tools))))
    return 0 if tools else 1


def imported_top_modules(path: Path) -> set:
    tops = set()
    for node in ast.walk(ast.parse(path.read_bytes())):
        if isinstance(node, ast.Import):
            tops |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            tops.add(node.module.split(".")[0])
    return tops


def cmd_assert_stdlib(args) -> int:
    bad = []
    for name in ("oracle.py", "certify.py"):
        p = HERE / name
        if not p.exists():
            bad.append("%s missing" % name)
            continue
        extra = imported_top_modules(p) - set(sys.stdlib_module_names) - {"__future__", "oracle"}
        bad += ["%s imports %s" % (name, m) for m in sorted(extra)]
    print("STDLIB-ONLY: %s" % ("PASS" if not bad else "FAIL " + "; ".join(bad)))
    return 1 if bad else 0


# ----------------------------------------------------------------------------- measurements (G0.P4)

MEASURE_TOOLS = {"ruff": "0.16.9", "basedpyright": "1.40.1", "ty": "0.0.84"}
TARGET_SELECT = ["E", "W", "F", "I", "UP", "B", "C4", "SIM", "PIE", "PERF", "RUF", "T10", "T20",
                 "ASYNC", "LOG", "G", "N", "A", "PT", "RET", "S", "BLE", "PTH", "TC", "ERA", "PGH",
                 "FLY", "ISC", "ICN", "Q"]
TARGET_IGNORE = ["E501", "ISC001", "Q000", "Q001", "Q002", "Q003", "COM812"]
STRETCH = ["D", "ANN", "ARG", "FBT", "TRY", "PL"]


def _uvx(tool, args, cwd, timeout=3600):
    return run(["uvx", "%s@%s" % (tool, MEASURE_TOOLS[tool]), *args], cwd=cwd, env=oracle_env(),
               timeout=timeout)


def _ruff_cfg(d: Path, select, target="py311", line_length=100) -> Path:
    cfg = d / ("ruff-%s-%d.toml" % ("-".join(select)[:20], line_length))
    cfg.write_text(
        'target-version = "%s"\nline-length = %d\n[lint]\nselect = %s\nignore = %s\n'
        '[lint.per-file-ignores]\n"tests/**" = ["S101"]\n"scripts/**" = ["T20"]\n' % (
            target, line_length, json.dumps(select), json.dumps(TARGET_IGNORE)), encoding="utf-8")
    return cfg


def _rule_counts(stdout: str) -> dict:
    counts = {}
    for d in json.loads(stdout or "[]"):
        code = d.get("code") or "syntax-error"
        counts[code] = counts.get(code, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))


def measure(ref: str) -> dict:
    out = {"ref": git("rev-parse", ref).strip(), "tools": MEASURE_TOOLS,
           "ruff_config": {"select": TARGET_SELECT, "ignore": TARGET_IGNORE,
                           "per_file_ignores": {"tests/**": ["S101"], "scripts/**": ["T20"]},
                           "target_version": "py311 (requires-python >=3.11)"}}
    cfgdir = Path(tempfile.mkdtemp(prefix="aurora-measure-cfg-"))
    try:
        with scratch_tree(out["ref"], "aurora-measure-") as t:
            inv = build_inventory(t)
            files = [f for f in inv["in_scope"] if (t / f).exists()]
            out["in_scope_files"] = len(files)
            out["in_scope_lines"] = sum(inv["files"][f]["lines"] for f in files)
            r = _uvx("ruff", ["check", "--config", str(_ruff_cfg(cfgdir, TARGET_SELECT)),
                              "--output-format", "json", "--exit-zero", *files], t)
            rules = _rule_counts(r.stdout)
            out["ruff_target"] = {"total": sum(rules.values()), "by_rule": rules}
            fam = {}
            for code, n in rules.items():
                f = re.match(r"[A-Z]+", code)
                f = f.group(0) if f else code
                fam[f] = fam.get(f, 0) + n
            out["ruff_target"]["by_prefix"] = dict(sorted(fam.items(), key=lambda kv: -kv[1]))
            r = _uvx("ruff", ["check", "--config", str(_ruff_cfg(cfgdir, STRETCH)),
                              "--output-format", "json", "--exit-zero", *files], t)
            stretch = {}
            for code, n in _rule_counts(r.stdout).items():
                f = next((x for x in sorted(STRETCH, key=len, reverse=True) if code.startswith(x)), code)
                stretch[f] = stretch.get(f, 0) + n
            out["ruff_stretch"] = stretch
            out["ruff_format"] = {}
            for ll in (100, 120):
                # concise output: ruff 0.16.9's default "full" renderer panics on two files
                # (ruff_annotate_snippets source_map.rs:185); the formatter itself does not
                r = _uvx("ruff", ["format", "--check", "--output-format", "concise", "--config",
                                  str(_ruff_cfg(cfgdir, ["E"], line_length=ll)), *files], t)
                text = r.stdout + r.stderr
                out["ruff_format"]["line_length_%d" % ll] = {
                    "would_reformat": len(re.findall(r"(?m): unformatted: File would be reformatted$", text)),
                    "errors": [ln for ln in text.splitlines() if ln.startswith("error")][:20],
                    "exit": r.returncode}
            pyr = cfgdir / "pyrightconfig.json"
            pyr.write_text(json.dumps({
                "include": [str(t / f) for f in files], "typeCheckingMode": "standard",
                "pythonVersion": "3.12", "venvPath": str(t), "venv": ".venv",
                "extraPaths": [str(t)]}), encoding="utf-8")
            # text output: basedpyright 1.40.1 dies in V8 (exit 245/251, no message) while
            # serialising --outputjson for this many diagnostics; the analysis itself completes
            r = _uvx("basedpyright", ["-p", str(pyr)], t)
            text = r.stdout + r.stderr
            m = re.search(r"(?m)^(\d+) errors?, (\d+) warnings?", text)
            by_rule = {}
            for rule in re.findall(r"(?m)^\s+\S.*? - error: .*?\((report\w+)\)\s*$", text):
                by_rule[rule] = by_rule.get(rule, 0) + 1
            out["basedpyright_standard"] = {
                "errors": int(m.group(1)) if m else None,
                "warnings": int(m.group(2)) if m else None,
                "exit": r.returncode,
                "by_rule_single_line": dict(sorted(by_rule.items(), key=lambda kv: -kv[1])),
                "note": "by_rule counts errors whose rule tag sits on the error line itself; "
                        "multi-line messages put it on a continuation line and are counted "
                        "in errors only"}
            r = _uvx("ty", ["check", "--python", str(venv_python(t)), "--output-format", "concise",
                            "--exit-zero", *files], t)
            m = re.search(r"Found (\d+) diagnostic", r.stdout + r.stderr)
            out["ty"] = {"diagnostics": int(m.group(1)) if m else None,
                         "tail": (r.stdout + r.stderr).strip().splitlines()[-1:] if not m else []}
    finally:
        _rmtree(cfgdir)
    return out


def suite_measurements(label: str) -> dict:
    """Durations (the 50 slowest tests, from run 1's junit xml) and coverage, from a snapshot."""
    import xml.etree.ElementTree as ET
    d = snapshot_dir(label)
    res = {}
    xml_path = d / "raw" / "O1-run1.xml"
    if xml_path.exists():
        cases = []
        for tc in ET.parse(xml_path).getroot().iter("testcase"):
            cases.append((float(tc.get("time", 0)), "%s::%s" % (tc.get("classname"), tc.get("name"))))
        cases.sort(reverse=True)
        res["slowest_50"] = [{"s": round(t, 2), "test": n} for t, n in cases[:50]]
    if (d / "O1.json").exists():
        res["suite_runs_s"] = [r["duration_s"] for r in load_json(d / "O1.json")["runs"]]
        res["outcome_counts"] = [r["counts"] for r in load_json(d / "O1.json")["runs"]]
    if (d / "O10.json").exists():
        res["coverage_branch_pct"] = load_json(d / "O10.json")["packages"]
    return res


def cmd_measure(args) -> int:
    m = measure(args.ref)
    m["suite"] = suite_measurements(args.label)
    dump_json(snapshot_dir(args.label) / "measurements.json", m)
    print(json.dumps({k: (v if not isinstance(v, dict) or len(json.dumps(v)) < 300 else
                          {kk: vv for kk, vv in v.items() if not isinstance(vv, (dict, list))})
                      for k, v in m.items() if k != "suite"}, indent=1))
    return 0


# ----------------------------------------------------------------------------- CLI

def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="oracle.py", description=__doc__.split("\n\n")[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("inventory", help="classify every tracked .py (writes inventory.json)")
    s.add_argument("--check", action="store_true", help="exit 1 if inventory.json is stale")
    s.add_argument("--verify-proofs", action="store_true", help="every ARCHIVAL entry has its proof")
    s = sub.add_parser("snapshot", help="capture oracle components into snapshots/<label>/")
    s.add_argument("label")
    s.add_argument("--ref", default="HEAD")
    s.add_argument("--runs", type=int, default=3)
    s.add_argument("--reruns", type=int, default=2)
    s.add_argument("--components")
    s.add_argument("--modules", help="restrict O3/O5 to these modules (impacted oracle)")
    s.add_argument("--select", help="test paths for O1/O10 (smoke only; verify-snapshot rejects it)")
    s.add_argument("--python", help="interpreter for the tree's venv (G1.P2 candidates)")
    s = sub.add_parser("compare", help="compare two snapshots component by component")
    s.add_argument("a")
    s.add_argument("b")
    s.add_argument("--components")
    s.add_argument("--partial", action="store_true", help="b is a module-restricted capture")
    s = sub.add_parser("ast-equal", help="AST-equality of every .py changed parent..commit")
    s.add_argument("parent")
    s.add_argument("commit")
    s = sub.add_parser("impacted", help="test files impacted by a commit (+ smoke set)")
    s.add_argument("commit")
    s = sub.add_parser("verify-snapshot", help="snapshot has every component, one tree")
    s.add_argument("label")
    s.add_argument("--suite-runs", type=int, default=3)
    s = sub.add_parser("selftest-d14", help="remove a public core function; expect O5 DIFF")
    s.add_argument("--baseline", default="g0")
    sub.add_parser("mcp-stdio", help="list MCP tools by launching the .mcp.json server")
    sub.add_parser("assert-stdlib", help="oracle.py and certify.py import only the stdlib")
    s = sub.add_parser("rekey-o1", help="hash parametrize text in a stored O1.json (idempotent)")
    s.add_argument("label")
    s = sub.add_parser("measure", help="G0.P4 tool numbers (ruff, format, basedpyright, ty)")
    s.add_argument("label")
    s.add_argument("--ref", default=None)
    args = p.parse_args(argv)
    return {
        "inventory": cmd_inventory, "snapshot": cmd_snapshot, "compare": cmd_compare,
        "ast-equal": cmd_ast_equal, "impacted": cmd_impacted,
        "verify-snapshot": cmd_verify_snapshot, "selftest-d14": cmd_selftest_d14,
        "mcp-stdio": cmd_mcp_stdio, "assert-stdlib": cmd_assert_stdlib, "measure": cmd_measure,
        "rekey-o1": cmd_rekey_o1,
    }[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
