"""check_doc_currency -- P4 (T024): no dead law under docs/.

The disease this kills (T016 F1c): docs/library/design/20260705_master-directive-list-akashic-aurora-202_964020.md declared itself
SINGLE SOURCE OF TRUTH for a lane model AGENTS.md had abolished, sat UNTRACKED, and a cold
agent reading docs/ chronologically would adopt dead law. The cure is a currency stamp every
doc must carry, near the top:

    Status: current                     an agent acting on it today acts correctly
    Status: superseded-by <path>        a newer doc covers this ground -- read that one
    Status: historical                  a record of its moment; correct then, not law now

FAILS (exit 1) on:  unstamped .md files under docs/;  UNTRACKED files under docs/
                    (invisible to peers is a defect);  superseded-by with no target path.
WARNS (exit 0) on:  current-stamped docs whose last git touch is older than STALE_DAYS
                    (default 45; env DOC_CURRENCY_STALE_DAYS, 0 disables).

Tolerant parse: bold/plain, with/without colon variants ("**Status:** current (...)"),
first 12 lines. VOCABULARY is strict on purpose -- one of current/superseded-by/historical;
prose like "Status: execution plan" is unstamped (stamp it properly).
Allowlist: autogenerated files whose generators own their content.
"""
import os
import re
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # T104-M1 depth
DOCS = os.path.join(ROOT, "docs")
STALE_DAYS = int(os.environ.get("DOC_CURRENCY_STALE_DAYS", "45"))
AUTOGEN = {"MODULE_INDEX.md"}   # regenerated by scripts/generators/gen_arch_index.py; generator owns it

STATUS_RE = re.compile(r"^\**\s*status\s*:?\**\s*:?\s*(.+?)\s*$", re.IGNORECASE)


def classify(path):
    """(verdict, detail) -- verdict in {current, superseded, historical, unstamped}."""
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            head = [next(f, "") for _ in range(12)]
    except OSError as e:
        return "unstamped", f"unreadable: {e}"
    for line in head:
        m = STATUS_RE.match(line.strip())
        if not m:
            continue
        value = m.group(1).strip()
        low = value.lower()
        if low.startswith("superseded"):
            target = re.search(r"superseded[- ]by:?\s*(\S+)", low)
            return ("superseded", target.group(1)) if target else ("superseded", "")
        if low.startswith("historical") or low.startswith("archived"):
            return "historical", value
        if low.startswith("current"):
            return "current", value
        return "unstamped", f"unrecognized status vocabulary: {value!r}"
    return "unstamped", "no Status line in the first 12 lines"


def last_git_touch_days(relpath):
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%ct", "--", relpath],
                             cwd=ROOT, capture_output=True, text=True, timeout=15).stdout.strip()
        return (time.time() - int(out)) / 86400 if out else None
    except Exception:
        return None


def untracked_docs():
    try:
        out = subprocess.run(["git", "ls-files", "--others", "--exclude-standard", "docs/"],
                             cwd=ROOT, capture_output=True, text=True, timeout=15).stdout
        return [l.strip() for l in out.splitlines() if l.strip()]
    except Exception:
        return []


def main() -> int:
    print("=" * 60)
    print("DOC-CURRENCY CHECK (docs/ carries no dead law)")
    print("=" * 60)
    failures, warnings = [], []

    # A NEW doc riding THIS ship is about to become tracked -- the guard runs before the
    # commit, so treat the ship's own staged paths as tracked (first tripped by the
    # RB-25 runbook registration: a new docs/ file could never pass ship.py otherwise).
    staged = {p.replace("\\", "/").lstrip("./") for p in sys.argv[1:]}
    for tracked in untracked_docs():
        if tracked.replace("\\", "/") in staged:
            continue
        failures.append(f"[untracked] {tracked} -- invisible to peers; commit it or delete it")

    for name in sorted(os.listdir(DOCS)):
        if not name.endswith(".md") or name in AUTOGEN:
            continue
        rel = f"docs/{name}"
        verdict, detail = classify(os.path.join(DOCS, name))
        if verdict == "unstamped":
            failures.append(f"[unstamped] {rel} -- {detail}")
        elif verdict == "superseded" and not detail:
            failures.append(f"[superseded-no-target] {rel} -- name the successor doc")
        elif verdict == "current" and STALE_DAYS:
            age = last_git_touch_days(rel)
            if age is not None and age > STALE_DAYS:
                warnings.append(f"[stale-current] {rel} -- claims current, untouched {age:.0f}d "
                                f"(> {STALE_DAYS}d): re-affirm or re-stamp")

    for w in warnings:
        print(f"WARN: {w}")
    if failures:
        for f_ in failures:
            print(f"FAIL: {f_}")
        print(f"\nFAIL: {len(failures)} doc-currency violation(s) "
              f"(stamp: Status: current | superseded-by <path> | historical)")
        return 1
    print(f"PASS: every docs/*.md is stamped and tracked "
          f"({len(warnings)} stale-current warning(s), {len(AUTOGEN)} autogen exempt).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
