import assert from 'node:assert/strict';
import { createGestureModel, createWorldJourney, harmonicColour, VOICE_CAPACITY } from '../arsenal/web/piano/spectacle-motion.js';
const dry = createGestureModel();
dry.noteOn(84, 117, 0); dry.noteOff(84, .12);
assert.equal(dry.notes.get(84).style, 1); assert.equal(dry.notes.get(84).end, .12);
const wet = createGestureModel();
wet.pedal(true, 0); wet.noteOn(84, 117, .1); wet.noteOff(84, .2);
assert.equal(wet.notes.get(84).style, 2); assert.equal(wet.notes.get(84).end, null);
wet.pedal(false, 2); assert.equal(wet.notes.get(84).end, 2);
const loud = createGestureModel(), soft = createGestureModel();
for (const m of [48, 60, 64, 67]) { loud.noteOn(m, 120, 0); soft.noteOn(m, 40, 0); }
loud.update(.1, .1, null); soft.update(.1, .1, null);
assert(loud.state.impact > soft.state.impact * 5); assert.equal(loud.impacts.length, 1);
for (let t = .2; t < 5; t += .1) soft.update(.1, t, null);
assert(soft.state.calm > .4);
soft.clear(5); for (let t = 5.1; t < 19; t += .1) soft.update(.1, t, null);
assert.equal(soft.notes.size, 0); assert(soft.state.energy < .01);
const major = {name:'C',root:{letter:0,acc:0},suffix:'',notes:[60,64,67].map(midi=>({midi}))};
const dom = {name:'G7',root:{letter:4,acc:0},suffix:'7',notes:[55,59,62,65].map(midi=>({midi}))};
const cadence = createGestureModel();
for(let t=0;t<1;t+=.1) cadence.update(.1,t,dom);
for(let t=1;t<1.7;t+=.1) cadence.update(.1,t,major);
assert(cadence.state.cadence>.6);
assert.equal(harmonicColour({...major,suffix:'maj7'}).minor,0);
assert.equal(harmonicColour({...major,suffix:'m9'}).minor,1);
const repeat=createGestureModel();repeat.noteOn(84,90,1);const firstStrike=repeat.notes.get(84);
repeat.noteOff(84,1.1);repeat.noteOn(84,70,1.2);
assert(repeat.voices?.includes(firstStrike),'a repeated pitch must retain the previous visual strike');
assert.equal(firstStrike.at,1);assert.equal(firstStrike.end,1.1);
assert.notEqual(repeat.notes.get(84),firstStrike);
assert.equal(repeat.notes.get(84).style,0);assert.equal(repeat.notes.get(84).end,null);
for(let i=0;i<3000;i++){repeat.noteOn(21+i%88,100,2+i*.1);repeat.update(.1,2+i*.1,null);}
assert(repeat.notes.size<=88);assert(repeat.impacts.length<=24);
assert(repeat.keyMotion.every((v,i)=>i%4!==3 || (v>=0&&v<1)),'periodic emission phase stays precise in long sessions');
const pressure=createGestureModel();pressure.noteOn(60,90,0);const oldest=pressure.voices[0];
for(let i=1;i<VOICE_CAPACITY+12;i++)pressure.noteOn(60,80,i*.001);
assert.equal(pressure.voices.filter(Boolean).length,VOICE_CAPACITY);
assert.equal(pressure.voices[0],oldest,'overflow must not overwrite retained strike history');
assert.equal(pressure.state.visualOverflow,12);
assert.equal(oldest.at,0);assert.equal(oldest.end,.001);
pressure.clear(1);pressure.update(.1,12,null);
assert.equal(pressure.voices.filter(Boolean).length,0);
const spring=createGestureModel();spring.noteOn(60,90,0);
for(let i=1;i<=120;i++)spring.update(1/60,i/60,null);
const height=spring.keyMotion[(60-21)*4],phase=spring.keyMotion[(60-21)*4+3];spring.noteOn(60,127,2.01);
assert.equal(spring.keyMotion[(60-21)*4],height,'re-strike adds momentum without resetting height');
assert.equal(spring.keyMotion[(60-21)*4+3],phase,'re-strike never rewinds the continuous emission phase');
spring.update(1/60,2.02,null);assert(Math.abs(spring.keyMotion[(60-21)*4]-height)<.2);
function atRate(rate){const m=createGestureModel();m.noteOn(60,100,0);for(let i=1;i<=rate;i++)m.update(1/rate,i/rate,null);return m.keyMotion[(60-21)*4];}
assert(Math.abs(atRate(30)-atRate(120))<.02,'spring response is stable across frame rates');
assert(loud.state.force>soft.state.force,'performance force follows velocity');
const travel=createWorldJourney(), storm={density:4,tension:.7,calm:0,energy:.2,minor:0,air:0};
assert.equal(travel(storm,0,'moon'),'moon');assert.equal(travel(storm,3,'moon'),'moon');assert.equal(travel(storm,4.1,'moon'),'rain');
const peaceful={...storm,tension:0,calm:.7};
assert.equal(travel(peaceful,5,'rain'),'rain');assert.equal(travel(peaceful,10,'rain'),'rain');assert.equal(travel(peaceful,19,'rain'),'moon');
assert.equal(travel({...storm,density:0},40,'moon'),'moon');
console.log('Spectacle gestures: velocity, dry/wet staccato, soft sustain, release, cadence, re-strikes and bounded history passed.');
