"""
renew_deepseek_solo -- run DeepSeek's INDEPENDENT Renew exploration in ISOLATION from the Bifrost bus.

Why: the shared bus runner (bifrost_runner_deepseek.py) is a singleton contended across sessions, so a
research brief gets crowded out by other sessions' asks (observed 2026-07-07). This driver instantiates
the SAME guarded agentic ToolBox+Agent directly (read-only, secret-blocked, path-scoped) and runs ONE
agentic turn to completion, then writes DeepSeek's final answer to the report file. No bus, no cursor,
no contention. Independent of, and concurrent with, whatever the shared runner is doing.

  py scripts/research/renew_deepseek_solo.py
"""
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# The Agent streams DeepSeek's thinking/tool-calls (which contain emoji) to stdout; on Windows the
# default cp1252 console encoding crashes on them. Force UTF-8 so a background run can't die on an emoji.
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SCRIPTS = os.path.join(REPO, "scripts")
sys.path.insert(0, REPO)
sys.path.insert(0, SCRIPTS)

import deepseek_chat as dc
from ask_deepseek import load_key

OUT = os.path.join(REPO, "research", "reviewed", "renew-deepseek-2026-07-07.md")

BRIEF = """INDEPENDENT RESEARCH ASK. Form your OWN view. Do NOT read my notes from today \
(research/reviewed/renew-priorart-2026-07-07.md, or the 'Renew' section of \
docs/agent-membrane-design-2026-07.md) until AFTER you've formed your own answer -- I want a genuine \
cross-check, not an echo.

QUESTION: A collaborator proposes that Aurora should manage each agent's CONTEXT LIFECYCLE for \
long-running work -- not just enforce a token limit, but estimate 'context health' (duplication, \
superseded plans, conflicting TODOs, noise) and, when an agent accumulates 'cognitive debt', do a \
curated SAVE (extract only durable knowledge) + RELAUNCH with a fresh working set. Four context tiers \
with different lifespans: Working / Session / Project / Historical. Refresh triggers beyond size: \
task-transition, branch-switch, architecture-change, policy-change.

YOUR TASK -- use your read tools to investigate the actual codebase (core/, docs/, agent_cli.py) and \
answer concretely:
1) How would this fold into our membrane design (the 4 jobs: Surface / Capture / Enforce / Unify)? Is \
it a NEW job, or already half-built like the membrane itself was?
2) What does Aurora ALREADY have that implements pieces of this? Name SPECIFIC modules you actually \
found by reading the code.
3) Prior art you know for LLM-agent context/memory lifecycle management, and how we differ. (Be honest \
about citation confidence -- do not invent paper titles/IDs.)
4) What is genuinely NEW that we'd have to build, and what research is needed FIRST?

Write your findings as a full, well-structured markdown report. Your FINAL message will be saved \
verbatim as the report file, so make the final message the complete report (headings, specifics, a \
graded Sources section). Investigate first, then write."""


def main() -> int:
    root = Path(REPO)
    client = dc.make_client(load_key())
    toolbox = dc.ToolBox(root, allow_exec=False, trust=False, allow_secrets=False,
                         confirm=lambda _p: False)          # read-only, auto-deny any confirm
    system = dc.default_system(root)

    def on_activity(state, detail=""):
        print(f"[solo] {state}: {str(detail)[:80]}", flush=True)

    def on_trace(kind, text):
        print(f"[solo:{kind}] {str(text)[:100]}", flush=True)

    ag = dc.Agent(client, toolbox, model=dc.PRO, system=system, think=True,
                  tools_enabled=True, on_activity=on_activity, on_trace=on_trace)

    print("[solo] starting isolated DeepSeek Renew exploration...", flush=True)
    answer = ag.send(BRIEF)
    if not answer or not answer.strip():
        print("[solo] ERROR: empty final answer", flush=True)
        return 1

    header = (f"# RENEW -- DeepSeek independent exploration (isolated run) - "
              f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n\n"
              f"> Generated by scripts/research/renew_deepseek_solo.py (off-bus, agentic read-only). "
              f"DeepSeek's verbatim final report follows.\n\n---\n\n")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header + answer.strip() + "\n")
    print(f"[solo] wrote {len(answer)} chars -> {OUT}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
